### ISSUE TITLE
Missing player_assist_ids and Cards for certain seasons

### ISSUE THREAD

**Issue by kirkyl93** [dcaribou/transfermarkt-datasets#316]
Thanks so much for providing these datasets, I've had a lot of fun playing around with them!

I've noticed that the following seasons are missing player_assist_ids and Cards in the game_events table across all competitions: 2014, 2015, 2016, 2017, 2019, 2020, 2021 and 2022 and wanted to let you know.

Give me a shout if you have any questions!

**Comment by dcaribou** [comment]
Thanks for reporting @kirkyl93.

**Comment by kirkyl93** [comment]
Hey @dcaribou, I've been able to spend some time looking into this and it just seems to be stale data stored in S3 for those seasons (maybe assists and cards were added later and the seasons haven't been refreshed since?).

I can see that when I run `dvc_pull` the raw games.json.gz does not contain any assist or card info. However, after running `make acquire_local ACQUIRER=transfermarkt-scraper ARGS="--seasons {relevant_season} --asset games` the assists and cards are present in the json file and are included in the prep step.

This is no longer an issue for me but let me know if I can help updating the games.json.gz file in S3.

Give me a shout if you have any questions!

**Comment by dcaribou** [comment]
I did a quick check and there does seem to be Card data missing, but only for a few seasons.
I haven't missed something, those season are (see aggregates below)

* For cards, seasons 2015, 2016, 2017 are missing
* For player assist ids, seasons 2015, 2016, 2017, 2020, 2021 are missing

|type|date_part('year', date)|count_star()|count(player_assist_id)|min(date)|max(date)|
|----|-----------------------|------------|-----------------------|---------|---------|
|Cards|2012|15432|0|2012-07-03|2012-12-30|
|Goals|2012|9792|7517|2012-07-03|2012-12-30|
|Substitutions|2012|19257|0|2012-07-03|2012-12-30|
|Cards|2013|24486|0|2013-01-01|2013-12-30|
|Goals|2013|15552|11995|2013-01-01|2013-12-30|
|Substitutions|2013|31760|0|2013-01-01|2013-12-30|
|Cards|2014|9643|0|2014-01-01|2014-05-24|
|Goals|2014|15164|5085|2014-01-01|2014-12-30|
|Substitutions|2014|31682|0|2014-01-01|2014-12-30|
|Goals|2015|15685|0|2015-01-01|2015-12-31|
|Substitutions|2015|32973|0|2015-01-01|2015-12-31|
|Goals|2016|15410|0|2016-01-02|2016-12-31|
|Substitutions|2016|32106|0|2016-01-02|2016-12-31|
|Goals|2017|16084|0|2017-01-01|2017-12-31|
|Substitutions|2017|33212|0|2017-01-01|2017-12-31|
|Cards|2018|15149|0|2018-06-26|2018-12-30|
|Goals|2018|15549|7102|2018-01-01|2018-12-30|
|Shootout|2018|707|0|2018-07-05|2018-12-19|
|Substitutions|2018|32213|0|2018-01-01|2018-12-30|
|Cards|2019|9373|0|2019-01-01|2019-05-29|
|Goals|2019|16180|4801|2019-01-01|2019-12-29|
|Shootout|2019|148|0|2019-01-16|2019-05-17|
|Substitutions|2019|32802|0|2019-01-01|2019-12-29|
|Goals|2020|13528|0|2020-01-01|2020-12-31|
|Substitutions|2020|34300|0|2020-01-01|2020-12-31|
|Cards|2021|10|0|2021-09-22|2021-09-22|
|Goals|2021|17606|3|2021-01-01|2021-12-31|
|Substitutions|2021|50256|0|2021-01-01|2021-12-31|
|Goals|2022|15334|0|2022-01-01|2022-12-31|
|Substitutions|2022|45541|0|2022-01-01|2022-12-31|
|Cards|2023|16092|0|2023-06-27|2023-12-31|
|Goals|2023|17758|7831|2023-01-01|2023-12-31|
|Shootout|2023|1334|0|2023-07-15|2023-12-19|
|Substitutions|2023|53394|0|2023-01-01|2023-12-31|
|Cards|2024|18245|0|2024-01-01|2024-12-07|
|Goals|2024|12333|9287|2024-01-01|2024-12-07|
|Shootout|2024|1248|0|2024-01-08|2024-10-16|
|Substitutions|2024|37609|0|2024-01-01|2024-12-07|

SQL query to get the aggregates
```sql
select 
	type,
	date_part('year', date),
	count(*),
	count(player_assist_id),
	min(date),
	max(date)
from dev.game_events
group by 1, 2
order by 2, 1
;
```

**Comment by kirkyl93** [comment]
Thanks for looking into this @dcaribou! I think the confusion might just have come about because of how we're defining season. I joined the game_events table with the games table and then filtered on season (from the games table). That doesn't align perfectly with a calendar year, which is why I think you're seeing entries for some seasons that I couldn't see from my side (and also explains the lower card count in 2014 for example, as I imagine this only includes cards in the backend of the 2013 season).

I tried again with the latest data from Kaggle and found cards and assists missing for the same seasons I mentioned earlier.

**Comment by dcaribou** [comment]
> I joined the game_events table with the games table and then filtered on season (from the games table)

This is actually the most accurate way to get the season 🙌 !

> maybe assists and cards were added later and the seasons haven't been refreshed since?

Yeah, most likely it is the case that I did not run a backfill when the new event type was introduced in the scraper. Thanks for raising this once again.

> This is no longer an issue for me but let me know if I can help updating the games.json.gz file in S3.

I just pushed a new version with the backfilled data for the missing seasons. Hopefully this solves the problem 😄.

**Comment by kirkyl93** [comment]
> I just pushed a new version with the backfilled data for the missing seasons. Hopefully this solves the problem 😄.

That's brilliant, thanks so much! I checked the latest Kaggle files and I can see that the cards and assists are now populated across seasons! The only season that appears to be still missing this data is the 2022 season now.

**Comment by dcaribou** [comment]
True. Pushed season 2022 as well 👍

**Comment by kirkyl93** [comment]
Wonderful! Appreciate the help :)
